[FLINK-21006][hbase] HBaseTablePlanTest is failed with NoSuchMethodError in haoop 3.1.3
This closes #14680

(cherry picked from commit c1b700ba0ba3e2361b82434441946eb26d25afea)